allowBuilds:
  '@alicloud/openapi-core': true
  '@ffmpeg-installer/darwin-arm64': true
  core-js: true
  core-js-pure: true
  electron: true
  electron-winstaller: true
  esbuild: true
  ffmpeg-static: true
  lfa-ponyfill: true
  msedge-tts: true
  protobufjs: true
nodeLinker: hoisted
