#!/usr/bin/env node

const path = require('node:path');
const { spawn } = require('node:child_process');

const nextBin = require.resolve('../node_modules/next/dist/bin/next');
const args = process.argv.slice(2);
if (args[0] === 'build' && !args.includes('--webpack')) args.push('--webpack');

const child = spawn(process.execPath, [nextBin, ...args], {
  cwd: process.cwd(),
  stdio: 'inherit',
  env: process.env,
});
child.on('exit', (code, signal) => {
  if (signal) process.kill(process.pid, signal);
  process.exit(code ?? 1);
});
